name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: install go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        check-latest: true
        cache: true

    - name: lint
      run: |
        make lint

    - name: build
      run: |
        make build
